### ISSUE TITLE
navigator.userAgentData is undefined

### ISSUE THREAD

**Issue by mphilipp622** [erossini/BlazorBrowserDetect#2]
Hi, I updated this package from 1.0.6 to 1.0.8 and a new error started popping up in my components that utilize the <BrowserDetect> component. In Firefox and Safari, the following error happens:

```
Unhandled exception rendering component: navigator.userAgentData is undefined
browserDetect@https://localhost:5003/_content/PSC.Blazor.Components.BrowserDetect/js/browserDetect.js:37:5
```

This is likely due to Firefox and Safari not supporting userAgentData as per Mozilla: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData

Although looking over this repo, nothing but the readme has changed for over a year. So, I don't know why this is happening all of a sudden. Any help would be appreciated. Thank you for the great package!

Edit 3/16/2023: I noticed the error pops up on the demo page on the repo: https://browserdetect.puresourcecode.com/
If you load that page with Firefox and inspect dev tools, you'll see the error.

**Comment by erossini** [comment]
Yes, it is right. A fix is on its way. I have to update the repo, you are right.
Let me know if it is working now.

**Comment by erossini** [comment]
In the next hour, I'm going to update the component with a generic version of the architecture and operating system version update.

**Comment by mphilipp622** [comment]
Hey, sorry for late reply. I just upgraded to 1.0.11 and it looks like the error has gone away. Thank you!
